/// Flutter icons NavikaIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavikaIcons
///      fonts:
///       - asset: fonts/NavikaIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class NavikaIcons {
  NavikaIcons._();

  static const _kFontFam = 'NavikaIcons';
  static const String? _kFontPkg = null;

  static const IconData business = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cable = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData city = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_filled = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cone = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cone_filled = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData e_bike = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorites = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData finish_flag = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_filled = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData localisation = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData localisation_null = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData marker = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData metro = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navette_fluviale = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noctilien = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData parking = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rer = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_filled = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_filled = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train_face = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train_rer = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tram = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData university = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walking = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_bookmark = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bike = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData options = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wheelchair = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData old_man = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData route_filled = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData route = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrival = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData departure = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData saved = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right = IconData(0xf054, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
