/// Flutter icons NavikaIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavikaIcons
///      fonts:
///       - asset: fonts/NavikaIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class NavikaIcons {
  NavikaIcons._();

  static const _kFontFam = 'NavikaIcons';
  static const String? _kFontPkg = null;

  static const IconData business = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idfmCable = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData city = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clockFilled = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cone = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coneFilled = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ebike = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorites = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData finishFlag = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeFilled = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData localisation = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData localisationNull = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData marker = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData metro = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idfmBoat = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idfmNoctilien = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData parking = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rer = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settingsFilled = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData starFilled = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idfmTrain = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trainFace = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idfmTrainRer = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idfmTram = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData university = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walking = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addBookmark = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bike = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idfmBus = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData options = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wheelchair = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oldMan = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData routeFilled = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData route = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrival = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData departure = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bellAdd = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bellFilled = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData avance = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telescope = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_2 = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leaf = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slide = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData past = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData futur = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData position_back = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData position_middle = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData position_front = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navi = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navi_1 = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData entrance = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData saved = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData busFace = IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right = IconData(0xf054, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
