/// Flutter icons Scaffold_icon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///	 fonts:
///		- family:	Scaffold_icon
///			fonts:
///			 - asset: fonts/Scaffold_icon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Scaffold_icon {
	Scaffold_icon._();

	static const _kFontFam = 'Scaffold_icon';
	static const String? _kFontPkg = null;

  static const IconData cone = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData correspondance = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gare = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
